BASE = ../..

NAME = net_unit

SRCS = main.cc inet_stream.cc inet.cc inetaddr.cc net_if.cc unix.cc

include $(BASE)/import/googletest/googletest/make.mk
include $(BASE)/net/make.mk

include $(BASE)/make/app.mk
