BASE = ../..

NAME = util_unit

SRCS = main.cc event.cc filedesc.cc fs.cc iohelper.cc iostream.cc logger.cc poller.cc safe_clib.cc

include $(BASE)/import/googletest/googletest/make.mk
include $(BASE)/util/make.mk

include $(BASE)/make/app.mk
